### ISSUE TITLE
Git large file storage over limit

### ISSUE THREAD

**Issue by fedderw** [BrookingsInstitution/activity-centers-data#1]
Hi! Thanks for posting your data, this is a really awesome project.

It looks like you're over your quote for git LFS, so it's not possible to download the larger files.

I was able to stitch together a new geojson for the block groups from the .rds file and the tiger line files, but it would be better to have the real thing.

A place you might be able to store for free is a database on dolthub

**Comment by afdta** [comment]
Hi, thanks for the interest! I've reposted the data in a repository with more available bandwidth: https://github.com/BrookingsMetro/activity-centers-data
